namespace PAM.Infos.GenresInfo;

public enum CinemaGenre
{
    ACAO,
    AVENTURA,
    CINEMA_DE_ARTE,
    CHANCHADA,
    COMEDIA,
    COMEDIA_DE_ACAO,
    COMEDIA_DE_TERROR,
    COMEDIA_DRAMATICA,
    COMEDIA_ROMANTICA,
    DANCA,
    DOCUMENTARIO,
    DOCUFICCAO,
    DRAMA,
    ESPIONAGEM,
    FAROESTE,
    FANTASIA,
    FANTASIA_CIENTIFICA,
    FICCAO_CIENTIFICA,
    FILMES_COM_TRUQUES,
    FILMES_DE_GUERRA,
    MISTERIO,
    MUSICAL,
    FILME_POLICIAL,
    ROMANCE,
    TERROR,
    THRILLER
}
